- name: conduct auth
  set_fact:
    uri: "{{ lookup('env', 'LDAP_URI') }}" 

- name: ddd
  debug:
    msg: "{{ uri }}" 
      

- name: Root suffix
  community.general.ldap_entry:
    dn: "{{ suffix }}"
    objectClass:
      - top
      - domain
    state: present
    server_uri: ldap://192.168.20.23:3389
    bind_dn: cn=Directory Manager
    bind_pw: boinkboink
  tags:
    - dir

- name: Make people OU
  community.general.ldap_entry:
    dn: "{{ people_ou }},{{ suffix }}"
    objectClass: organizationalUnit
    state: present
  args: "{{ ldap_auth }}"
  tags:
    - dir

- name: Make group OU
  community.general.ldap_entry:
    dn: "{{ group_ou }},{{ suffix }}"
    objectClass: organizationalUnit
    state: present
  args: "{{ ldap_auth }}"
  tags:
    - dir

- name: Label groups
  community.general.ldap_entry:
    dn: "cn={{ item.name }},{{ group_ou }},{{ suffix }}"
    objectClass:
      - groupOfNames
    attributes:
      cn: "{{ item.name }}"
      description: "{{ item.descr }}"
      member: "cn=piet,ou=people,dc=platform"
    state: present
  args: "{{ ldap_auth }}"
  loop: "{{ ldap_groups }}"
  tags:
    - dir

- name: PosixUsers
  community.general.ldap_entry:
    dn: "cn={{ item.name }},{{ people_ou }},{{ suffix }}"
    objectClass:
      - posixAccount
    attributes:
      cn: "{{ item.name }}"
      uid: "{{ item.name }}"
      uidNumber: "{{ item.uidNumber }}"
      gidNumber: "{{ item.gidNumber }}"
      userPassword: "{{ item.userPassword }}"
      homeDirectory: "/home/{{ item.name }}"
    state: present
  args: "{{ ldap_auth }}"
  loop: "{{ ldap_users }}"
  tags:
    - dir

- name: Fetch users from LDAP
  community.general.ldap_search:
    dn: "{{ people_ou }},{{ suffix }}"
    scope: "children"
    filter: "(objectClass=posixAccount)"
    attrs:
    - "cn"
  args: "{{ ldap_auth }}"
  register: ldap_uids
  tags:
    - debug
    - dir

- name: Collect user names from inventory
  set_fact:
    local_users: "{{ ldap_users | selectattr('name') | map(attribute='name') }}"
  tags:
    - debug
    - dir

- name: LDAP user names
  set_fact:
    ldap_users: "{{ ldap_uids.results | selectattr('cn') | map(attribute='cn') }}"
  tags:
    - debug
    - dir

- name: Remove legacy people
  community.general.ldap_entry:
    dn: "cn={{ item }},{{ people_ou }},{{ suffix }}"
    objectClass:
      - posixAccount
    state: absent
  args: "{{ ldap_auth }}"
  when: not item in local_users
  loop: "{{ ldap_users }}"
  tags:
    - debug
    - dir
